# See: https://docs.codecov.io/docs/codecov-yaml
# Validate using `curl -X POST --data-binary @.codecov.yml https://codecov.io/validate`
codecov:
  branch: master

# Do not post comments in PRs.
# TODO: Enable again once code coverage is more accurate.
comment: off
