[workspace]
members = [
    "primefield",
    "ecc",
]

# Don't forget to run `cargo clean` to force a rebuild of all dependencies!
[profile.release]
opt-level = 3
lto = true
debug = true # Debug symbols are required for profiling. Remove for production!
