[package]
name = "starkcrypto"
version = "0.1.0"
authors = ["Remco Bloemen <remco@0x.org>"]
edition = "2018"

[workspace]
members = [
    "wasm",
]

[dependencies]
num = "0.2.0"
num-bigint = "0.2"
hex-literal = "0.1.4"

[dev-dependencies]
rand = "0.6.5"
quickcheck = "0.8"
quickcheck_macros = "0.8"
criterion = "0.2.10"

[[bench]]
name = "benchmark"
harness = false
