[workspace]
members = [
    "utils/macros_lib",
    "utils/macros_impl",
    "utils/macros_decl",
    "utils/criterion_utils",
    "utils/logging_alloc",
    "utils/mmap_vec",
    "algebra/u256",
    "algebra/primefield",
    "algebra/curves",
    "crypto/merkle_tree",
    "crypto/ecc",
    "openstark",
    "0xchain/starkdex",
    "0xchain/substrate-node",
    "0xchain/substrate-runtime",
]

[profile.release]
opt-level = 3
lto = true
panic = 'unwind'

# HACK: Patch replace substrate's dependency on hex-literal with a local clone
# that sets #[no_std].
# TODO: Remove pending merger of https://github.com/RustCrypto/utils/pull/30
[replace]
"hex-literal:0.1.4" = { path = "./vendor/hex-literal" }
