[workspace]
members = [
    "primefield",
    "ecc",
    "starkdex",
    "stark",
    "macros_decl",
    "macros_impl",
    "macros_lib",
    "substrate-node",
    "substrate-runtime",
]

# Don't forget to run `cargo clean` to force a rebuild of all dependencies!
[profile.release]
opt-level = 3
lto = true
panic = 'unwind'
