/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface ConstraintPolyLen256Interface extends Interface {
  functions: {};

  events: {};
}

export class ConstraintPolyLen256 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): ConstraintPolyLen256;
  attach(addressOrName: string): ConstraintPolyLen256;
  deployed(): Promise<ConstraintPolyLen256>;

  on(event: EventFilter | string, listener: Listener): ConstraintPolyLen256;
  once(event: EventFilter | string, listener: Listener): ConstraintPolyLen256;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): ConstraintPolyLen256;
  removeAllListeners(eventName: EventFilter | string): ConstraintPolyLen256;
  removeListener(eventName: any, listener: Listener): ConstraintPolyLen256;

  interface: ConstraintPolyLen256Interface;

  functions: {};

  filters: {};

  estimate: {};
}
