/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface FriInterface extends Interface {
  functions: {};

  events: {
    LogTrace: TypedEventDescription<{
      encodeTopics([name, enter, gasLeft, allocated]: [
        null,
        null,
        null,
        null
      ]): string[];
    }>;
  };
}

export class Fri extends Contract {
  connect(signerOrProvider: Signer | Provider | string): Fri;
  attach(addressOrName: string): Fri;
  deployed(): Promise<Fri>;

  on(event: EventFilter | string, listener: Listener): Fri;
  once(event: EventFilter | string, listener: Listener): Fri;
  addListener(eventName: EventFilter | string, listener: Listener): Fri;
  removeAllListeners(eventName: EventFilter | string): Fri;
  removeListener(eventName: any, listener: Listener): Fri;

  interface: FriInterface;

  functions: {};

  filters: {
    LogTrace(
      name: null,
      enter: null,
      gasLeft: null,
      allocated: null
    ): EventFilter;
  };

  estimate: {};
}
