/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractFactory, Signer } from "ethers";
import { Provider } from "ethers/providers";
import { UnsignedTransaction } from "ethers/utils/transaction";

import { TransactionOverrides } from ".";
import { Fri } from "./Fri";

export class FriFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: TransactionOverrides): Promise<Fri> {
    return super.deploy(overrides) as Promise<Fri>;
  }
  getDeployTransaction(overrides?: TransactionOverrides): UnsignedTransaction {
    return super.getDeployTransaction(overrides);
  }
  attach(address: string): Fri {
    return super.attach(address) as Fri;
  }
  connect(signer: Signer): FriFactory {
    return super.connect(signer) as FriFactory;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Fri {
    return new Contract(address, _abi, signerOrProvider) as Fri;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "name",
        type: "bytes32"
      },
      {
        indexed: false,
        internalType: "bool",
        name: "enter",
        type: "bool"
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "gasLeft",
        type: "uint256"
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "allocated",
        type: "uint256"
      }
    ],
    name: "LogTrace",
    type: "event"
  }
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea26469706673582212202153e8298ff3b1663d39579d7453bd515d3fb0daf21e6eaa10af975991fcd41364736f6c63430006060033";
