/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractFactory, Signer } from "ethers";
import { Provider } from "ethers/providers";
import { UnsignedTransaction } from "ethers/utils/transaction";

import { TransactionOverrides } from ".";
import { MerkleVerifier } from "./MerkleVerifier";

export class MerkleVerifierFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: TransactionOverrides): Promise<MerkleVerifier> {
    return super.deploy(overrides) as Promise<MerkleVerifier>;
  }
  getDeployTransaction(overrides?: TransactionOverrides): UnsignedTransaction {
    return super.getDeployTransaction(overrides);
  }
  attach(address: string): MerkleVerifier {
    return super.attach(address) as MerkleVerifier;
  }
  connect(signer: Signer): MerkleVerifierFactory {
    return super.connect(signer) as MerkleVerifierFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MerkleVerifier {
    return new Contract(address, _abi, signerOrProvider) as MerkleVerifier;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "name",
        type: "bytes32"
      },
      {
        indexed: false,
        internalType: "bool",
        name: "enter",
        type: "bool"
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "gasLeft",
        type: "uint256"
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "allocated",
        type: "uint256"
      }
    ],
    name: "LogTrace",
    type: "event"
  }
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea264697066735822122019f0a2edf2f1563ddbf9b308c5598a1e0f9d848782a39c51f4ddb0e6d73be61464736f6c63430006060033";
