/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractFactory, Signer } from "ethers";
import { Provider } from "ethers/providers";
import { UnsignedTransaction } from "ethers/utils/transaction";

import { TransactionOverrides } from ".";
import { PrimeFieldTester } from "./PrimeFieldTester";

export class PrimeFieldTesterFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: TransactionOverrides): Promise<PrimeFieldTester> {
    return super.deploy(overrides) as Promise<PrimeFieldTester>;
  }
  getDeployTransaction(overrides?: TransactionOverrides): UnsignedTransaction {
    return super.getDeployTransaction(overrides);
  }
  attach(address: string): PrimeFieldTester {
    return super.attach(address) as PrimeFieldTester;
  }
  connect(signer: Signer): PrimeFieldTesterFactory {
    return super.connect(signer) as PrimeFieldTesterFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PrimeFieldTester {
    return new Contract(address, _abi, signerOrProvider) as PrimeFieldTester;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "data",
        type: "bytes32"
      }
    ],
    name: "log_bytes32",
    type: "event"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "b",
        type: "uint256"
      }
    ],
    name: "fadd_external",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    stateMutability: "pure",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "b",
        type: "uint256"
      }
    ],
    name: "fmul_external",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    stateMutability: "pure",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "b",
        type: "uint256"
      }
    ],
    name: "fpow_external",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a",
        type: "uint256"
      }
    ],
    name: "inverse_external",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  }
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102f2806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c806301e7f8631461005157806352743ada146100865780635f82eac2146100ab578063b129f702146100ce575b600080fd5b6100746004803603604081101561006757600080fd5b50803590602001356100eb565b60408051918252519081900360200190f35b6100a96004803603604081101561009c57600080fd5b5080359060200135610104565b005b610074600480360360408110156100c157600080fd5b508035906020013561014a565b6100a9600480360360208110156100e457600080fd5b503561015c565b60006100fd838363ffffffff61019a16565b9392505050565b7fe81699b85113eea1c73e10588b2b035e55893369632173afd43feb192fac64e3610135838363ffffffff6101c716565b60408051918252519081900360200190a15050565b60006100fd838363ffffffff6101f416565b7fe81699b85113eea1c73e10588b2b035e55893369632173afd43feb192fac64e361018682610221565b60408051918252519081900360200190a150565b60007f08000000000000110000000000000000000000000000000000000000000000018284099392505050565b60006100fd83837f0800000000000011000000000000000000000000000000000000000000000001610274565b60007f08000000000000110000000000000000000000000000000000000000000000018284089392505050565b600061026e827f0800000000000010ffffffffffffffffffffffffffffffffffffffffffffffff7f0800000000000011000000000000000000000000000000000000000000000001610274565b92915050565b600060405160208152602080820152602060408201528460608201528360808201528260a082015260208160c08360006005600019f16102b357600080fd5b5194935050505056fea264697066735822122095d4f518382c4140101a58529a106f66372baac28a8e4e286f40e1b1fab95a1764736f6c63430006060033";
