/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface StarkdexOodsPolyInterface extends Interface {
  functions: {};

  events: {};
}

export class StarkdexOodsPoly extends Contract {
  connect(signerOrProvider: Signer | Provider | string): StarkdexOodsPoly;
  attach(addressOrName: string): StarkdexOodsPoly;
  deployed(): Promise<StarkdexOodsPoly>;

  on(event: EventFilter | string, listener: Listener): StarkdexOodsPoly;
  once(event: EventFilter | string, listener: Listener): StarkdexOodsPoly;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): StarkdexOodsPoly;
  removeAllListeners(eventName: EventFilter | string): StarkdexOodsPoly;
  removeListener(eventName: any, listener: Listener): StarkdexOodsPoly;

  interface: StarkdexOodsPolyInterface;

  functions: {};

  filters: {};

  estimate: {};
}
