/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface StarkdexPeriodic3Interface extends Interface {
  functions: {
    evaluate: TypedFunctionDescription<{ encode([x]: [BigNumberish]): string }>;
  };

  events: {};
}

export class StarkdexPeriodic3 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): StarkdexPeriodic3;
  attach(addressOrName: string): StarkdexPeriodic3;
  deployed(): Promise<StarkdexPeriodic3>;

  on(event: EventFilter | string, listener: Listener): StarkdexPeriodic3;
  once(event: EventFilter | string, listener: Listener): StarkdexPeriodic3;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): StarkdexPeriodic3;
  removeAllListeners(eventName: EventFilter | string): StarkdexPeriodic3;
  removeListener(eventName: any, listener: Listener): StarkdexPeriodic3;

  interface: StarkdexPeriodic3Interface;

  functions: {
    evaluate(x: BigNumberish): Promise<BigNumber>;
  };

  evaluate(x: BigNumberish): Promise<BigNumber>;

  filters: {};

  estimate: {
    evaluate(x: BigNumberish): Promise<BigNumber>;
  };
}
