/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {Contract, ContractTransaction, EventFilter, Signer} from 'ethers';
import {Listener, Provider} from 'ethers/providers';
import {Arrayish, BigNumber, BigNumberish, Interface} from 'ethers/utils';
import {TransactionOverrides, TypedEventDescription, TypedFunctionDescription} from '.';

interface StarkDigestTestingInterface extends Interface {
    functions: {
        digest_read: TypedFunctionDescription<{
            encode([proof, constraints]: [
                {
                    public_inputs: Arrayish;
                    trace_values: BigNumberish[];
                    trace_commitment: Arrayish;
                    constraint_values: BigNumberish[];
                    constraint_commitment: Arrayish;
                    trace_oods_values: BigNumberish[];
                    constraint_oods_values: BigNumberish[];
                    pow_nonce: Arrayish;
                    trace_decommitment: Arrayish[];
                    constraint_decommitment: Arrayish[];
                    fri_values: BigNumberish[][];
                    fri_commitments: Arrayish[];
                    fri_decommitments: Arrayish[][];
                    last_layer_coeffiencts: BigNumberish[];
                },
                string,
            ]): string;
        }>;

        queries_read: TypedFunctionDescription<{
            encode([proof, constraints]: [
                {
                    public_inputs: Arrayish;
                    trace_values: BigNumberish[];
                    trace_commitment: Arrayish;
                    constraint_values: BigNumberish[];
                    constraint_commitment: Arrayish;
                    trace_oods_values: BigNumberish[];
                    constraint_oods_values: BigNumberish[];
                    pow_nonce: Arrayish;
                    trace_decommitment: Arrayish[];
                    constraint_decommitment: Arrayish[];
                    fri_values: BigNumberish[][];
                    fri_commitments: Arrayish[];
                    fri_decommitments: Arrayish[][];
                    last_layer_coeffiencts: BigNumberish[];
                },
                string,
            ]): string;
        }>;

        verify_proof: TypedFunctionDescription<{
            encode([proof, constraints]: [
                {
                    public_inputs: Arrayish;
                    trace_values: BigNumberish[];
                    trace_commitment: Arrayish;
                    constraint_values: BigNumberish[];
                    constraint_commitment: Arrayish;
                    trace_oods_values: BigNumberish[];
                    constraint_oods_values: BigNumberish[];
                    pow_nonce: Arrayish;
                    trace_decommitment: Arrayish[];
                    constraint_decommitment: Arrayish[];
                    fri_values: BigNumberish[][];
                    fri_commitments: Arrayish[];
                    fri_decommitments: Arrayish[][];
                    last_layer_coeffiencts: BigNumberish[];
                },
                string,
            ]): string;
        }>;
    };

    events: {};
}

export class StarkDigestTesting extends Contract {
    connect(signerOrProvider: Signer | Provider | string): StarkDigestTesting;
    attach(addressOrName: string): StarkDigestTesting;
    deployed(): Promise<StarkDigestTesting>;

    on(event: EventFilter | string, listener: Listener): StarkDigestTesting;
    once(event: EventFilter | string, listener: Listener): StarkDigestTesting;
    addListener(eventName: EventFilter | string, listener: Listener): StarkDigestTesting;
    removeAllListeners(eventName: EventFilter | string): StarkDigestTesting;
    removeListener(eventName: any, listener: Listener): StarkDigestTesting;

    interface: StarkDigestTestingInterface;

    functions: {
        digest_read(
            proof: {
                public_inputs: Arrayish;
                trace_values: BigNumberish[];
                trace_commitment: Arrayish;
                constraint_values: BigNumberish[];
                constraint_commitment: Arrayish;
                trace_oods_values: BigNumberish[];
                constraint_oods_values: BigNumberish[];
                pow_nonce: Arrayish;
                trace_decommitment: Arrayish[];
                constraint_decommitment: Arrayish[];
                fri_values: BigNumberish[][];
                fri_commitments: Arrayish[];
                fri_decommitments: Arrayish[][];
                last_layer_coeffiencts: BigNumberish[];
            },
            constraints: string,
        ): Promise<string>;

        queries_read(
            proof: {
                public_inputs: Arrayish;
                trace_values: BigNumberish[];
                trace_commitment: Arrayish;
                constraint_values: BigNumberish[];
                constraint_commitment: Arrayish;
                trace_oods_values: BigNumberish[];
                constraint_oods_values: BigNumberish[];
                pow_nonce: Arrayish;
                trace_decommitment: Arrayish[];
                constraint_decommitment: Arrayish[];
                fri_values: BigNumberish[][];
                fri_commitments: Arrayish[];
                fri_decommitments: Arrayish[][];
                last_layer_coeffiencts: BigNumberish[];
            },
            constraints: string,
        ): Promise<BigNumber[]>;

        verify_proof(
            proof: {
                public_inputs: Arrayish;
                trace_values: BigNumberish[];
                trace_commitment: Arrayish;
                constraint_values: BigNumberish[];
                constraint_commitment: Arrayish;
                trace_oods_values: BigNumberish[];
                constraint_oods_values: BigNumberish[];
                pow_nonce: Arrayish;
                trace_decommitment: Arrayish[];
                constraint_decommitment: Arrayish[];
                fri_values: BigNumberish[][];
                fri_commitments: Arrayish[];
                fri_decommitments: Arrayish[][];
                last_layer_coeffiencts: BigNumberish[];
            },
            constraints: string,
            overrides?: TransactionOverrides,
        ): Promise<ContractTransaction>;
    };

    digest_read(
        proof: {
            public_inputs: Arrayish;
            trace_values: BigNumberish[];
            trace_commitment: Arrayish;
            constraint_values: BigNumberish[];
            constraint_commitment: Arrayish;
            trace_oods_values: BigNumberish[];
            constraint_oods_values: BigNumberish[];
            pow_nonce: Arrayish;
            trace_decommitment: Arrayish[];
            constraint_decommitment: Arrayish[];
            fri_values: BigNumberish[][];
            fri_commitments: Arrayish[];
            fri_decommitments: Arrayish[][];
            last_layer_coeffiencts: BigNumberish[];
        },
        constraints: string,
    ): Promise<string>;

    queries_read(
        proof: {
            public_inputs: Arrayish;
            trace_values: BigNumberish[];
            trace_commitment: Arrayish;
            constraint_values: BigNumberish[];
            constraint_commitment: Arrayish;
            trace_oods_values: BigNumberish[];
            constraint_oods_values: BigNumberish[];
            pow_nonce: Arrayish;
            trace_decommitment: Arrayish[];
            constraint_decommitment: Arrayish[];
            fri_values: BigNumberish[][];
            fri_commitments: Arrayish[];
            fri_decommitments: Arrayish[][];
            last_layer_coeffiencts: BigNumberish[];
        },
        constraints: string,
    ): Promise<BigNumber[]>;

    verify_proof(
        proof: {
            public_inputs: Arrayish;
            trace_values: BigNumberish[];
            trace_commitment: Arrayish;
            constraint_values: BigNumberish[];
            constraint_commitment: Arrayish;
            trace_oods_values: BigNumberish[];
            constraint_oods_values: BigNumberish[];
            pow_nonce: Arrayish;
            trace_decommitment: Arrayish[];
            constraint_decommitment: Arrayish[];
            fri_values: BigNumberish[][];
            fri_commitments: Arrayish[];
            fri_decommitments: Arrayish[][];
            last_layer_coeffiencts: BigNumberish[];
        },
        constraints: string,
        overrides?: TransactionOverrides,
    ): Promise<ContractTransaction>;

    filters: {};

    estimate: {
        digest_read(
            proof: {
                public_inputs: Arrayish;
                trace_values: BigNumberish[];
                trace_commitment: Arrayish;
                constraint_values: BigNumberish[];
                constraint_commitment: Arrayish;
                trace_oods_values: BigNumberish[];
                constraint_oods_values: BigNumberish[];
                pow_nonce: Arrayish;
                trace_decommitment: Arrayish[];
                constraint_decommitment: Arrayish[];
                fri_values: BigNumberish[][];
                fri_commitments: Arrayish[];
                fri_decommitments: Arrayish[][];
                last_layer_coeffiencts: BigNumberish[];
            },
            constraints: string,
        ): Promise<BigNumber>;

        queries_read(
            proof: {
                public_inputs: Arrayish;
                trace_values: BigNumberish[];
                trace_commitment: Arrayish;
                constraint_values: BigNumberish[];
                constraint_commitment: Arrayish;
                trace_oods_values: BigNumberish[];
                constraint_oods_values: BigNumberish[];
                pow_nonce: Arrayish;
                trace_decommitment: Arrayish[];
                constraint_decommitment: Arrayish[];
                fri_values: BigNumberish[][];
                fri_commitments: Arrayish[];
                fri_decommitments: Arrayish[][];
                last_layer_coeffiencts: BigNumberish[];
            },
            constraints: string,
        ): Promise<BigNumber>;

        verify_proof(
            proof: {
                public_inputs: Arrayish;
                trace_values: BigNumberish[];
                trace_commitment: Arrayish;
                constraint_values: BigNumberish[];
                constraint_commitment: Arrayish;
                trace_oods_values: BigNumberish[];
                constraint_oods_values: BigNumberish[];
                pow_nonce: Arrayish;
                trace_decommitment: Arrayish[];
                constraint_decommitment: Arrayish[];
                fri_values: BigNumberish[][];
                fri_commitments: Arrayish[];
                fri_decommitments: Arrayish[][];
                last_layer_coeffiencts: BigNumberish[];
            },
            constraints: string,
        ): Promise<BigNumber>;
    };
}
