/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface TraceInterface extends Interface {
  functions: {};

  events: {
    LogTrace: TypedEventDescription<{
      encodeTopics([name, enter, gasLeft, allocated]: [
        null,
        null,
        null,
        null
      ]): string[];
    }>;
  };
}

export class Trace extends Contract {
  connect(signerOrProvider: Signer | Provider | string): Trace;
  attach(addressOrName: string): Trace;
  deployed(): Promise<Trace>;

  on(event: EventFilter | string, listener: Listener): Trace;
  once(event: EventFilter | string, listener: Listener): Trace;
  addListener(eventName: EventFilter | string, listener: Listener): Trace;
  removeAllListeners(eventName: EventFilter | string): Trace;
  removeListener(eventName: any, listener: Listener): Trace;

  interface: TraceInterface;

  functions: {};

  filters: {
    LogTrace(
      name: null,
      enter: null,
      gasLeft: null,
      allocated: null
    ): EventFilter;
  };

  estimate: {};
}
