[package]
name = "macros-decl"
version = "0.1.0"
authors = ["Remco Bloemen <remco@0x.org>"]
edition = "2018"

[dependencies]
proc-macro-hack = "0.5"
macros-impl = { path = "../macros_impl" }

[features]
default = ["std"]
std = []
